### ISSUE TITLE
Question: Any idea why the API requires "agreement_agreement: 1"?

### ISSUE THREAD

**Issue by TimSoethout** [dylian94/domoticz-GoodWeSEMS#13]
Hi Dylian,

Thanks for you plugin. I'm the maintainer of a similar plugin for HomeAssistant. :) (https://github.com/TimSoethout/goodwe-sems-home-assistant)

When I do the post to `/api/v2/Common/CrossLogin` I only send `account` and `pwd` but not the `is_local` and `agreement_agreement` fields. It does seem to work. In a previous version I do send the `agreement_agreement`.

However, now some of my users have issues with the login token expiring too quickly. Do the extra field with this maybe?

I hope we can swap notes this way and you might have any clues on this. :)

**Comment by TimSoethout** [comment]
I also have the idea that using user agent `ios` somehow makes it more stable. Maybe the api is more lenient to iOS clients.

**Comment by JanJaapKo** [comment]
Hi @TimSoethout ,

This plugin does not seem to be maintained anymore by @dylian94 . Some people use my [fork](https://github.com/JanJaapKo/domoticz-GoodWeSEMS) and issues are tracked via the [domoticz forum](https://www.domoticz.com/forum/viewtopic.php?f=65&t=28983&start=80). I did not get any complaints about failing login tokens or instable API so far.

Having said that, sure we can swap notes ;)

**Comment by dylian94** [comment]
Indeed at first I was unable to maintain the plugin due too different priorities, and more recently we moved so I don't own a GoodWe inverter anymore.
