### ISSUE TITLE
Total generation not visable?

### ISSUE THREAD

**Issue by hcroij** [dylian94/domoticz-GoodWeSEMS#4]
**Describe the bug**

Tried to figure out myself but (ofcourse) could not find the solution.
Although the "Devices" (Apparaten) tab shows the total generation of my panels over the years (12475.100kWh) the representation of it shows only the daily generation.
Hope the pictures explain.

![totaal 2](https://user-images.githubusercontent.com/14148586/68024081-5824f380-fca9-11e9-9c74-0d76d18a5e15.JPG)
![totaal switch](https://user-images.githubusercontent.com/14148586/68024086-5c511100-fca9-11e9-88a4-804cb3f3038d.JPG)
I tried to play around with the line :
Devices[self.baseDeviceIndex + 4].Update(nValue=0, sValue=str(inverter["output_power"]) + ";" + str(inverter["etotal"] * 1000))
In the python script, but (I cleared cache in the browser) this did not work for me.
I did some logging on it and found the following line in the log:

2019-11-01 12:27:47.073 (Totaal gegenereerd Paneel) Updating device from 0:'382W;12475200.0' to have values 0:'392W;12475300.0'.
So looking at this, the update is correct but the "Domotics switch" shows only the first value (382W) and disregarding the second value (12475300)

**Domoticz environment Raspberry PI (please complete the following information):**

 - Domoticz Version: e.g. 4.10717]
 - Python Version: e.g. 3.4.4

**Comment by dylian94** [comment]
This just how Domoticz works, as far as I know this is not related to this plugin.

**Comment by hcroij** [comment]
thx for the quick response
Ill bring it to domoticz forum
